# Generated by Django 6.0.3 on 2026-04-06 18:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0002_tratamiento_cita_observaciones_doctor_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DienteEstado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diente', models.IntegerField()),
                ('estado', models.CharField(choices=[('Sano', 'Sano'), ('Caries', 'Caries (Rojo)'), ('Resina', 'Resina/Empaste (Azul)'), ('Extraccion', 'Para Extracción (Naranja)'), ('Ausente', 'Ausente (Negro)'), ('Corona', 'Corona (Amarillo)')], default='Sano', max_length=20)),
                ('notas', models.CharField(blank=True, help_text='Ej: Cara oclusal, dolor agudo...', max_length=100, null=True)),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='odontograma', to='gestion.paciente')),
            ],
            options={
                'unique_together': {('paciente', 'diente')},
            },
        ),
    ]
