# Generated by Django 6.0.3 on 2026-04-06 20:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0004_pago'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArchivoPaciente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(help_text='Ej. Radiografía Panorámica, Examen de Sangre...', max_length=100)),
                ('archivo', models.FileField(upload_to='pacientes_archivos/')),
                ('fecha_subida', models.DateTimeField(auto_now_add=True)),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='archivos', to='gestion.paciente')),
            ],
        ),
    ]
