# Generated by Django 6.0.3 on 2026-04-07 06:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0005_archivopaciente'),
    ]

    operations = [
        migrations.CreateModel(
            name='Receta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('prescripcion', models.TextField(help_text='Ej: Ibuprofeno 400mg - 1 pastilla cada 8 horas por 3 días')),
                ('notas_adicionales', models.TextField(blank=True, help_text='Recomendaciones (reposo, dieta, etc.)', null=True)),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recetas', to='gestion.paciente')),
            ],
        ),
    ]
