# Generated by Django 6.0.3 on 2026-04-07 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0006_receta'),
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('cantidad_actual', models.IntegerField(default=0)),
                ('stock_minimo', models.IntegerField(default=5)),
                ('precio_compra', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('ultima_actualizacion', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
