# Generated by Django 6.0.3 on 2026-04-07 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0008_materialtratamiento'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='archivopaciente',
            name='archivo',
        ),
        migrations.AddField(
            model_name='archivopaciente',
            name='imagen',
            field=models.ImageField(default='', upload_to='pacientes/evidencia/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='archivopaciente',
            name='titulo',
            field=models.CharField(max_length=100, verbose_name='Nombre del estudio/foto'),
        ),
    ]
