# Generated by Django 6.0.3 on 2026-04-07 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0009_remove_archivopaciente_archivo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='archivopaciente',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='pacientes/evidencia/'),
        ),
        migrations.AlterField(
            model_name='archivopaciente',
            name='titulo',
            field=models.CharField(max_length=100),
        ),
    ]
