# Generated by Django 6.0.3 on 2026-04-08 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0010_alter_archivopaciente_imagen_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dienteestado',
            options={'ordering': ['numero_diente']},
        ),
        migrations.AlterUniqueTogether(
            name='dienteestado',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='dienteestado',
            name='fecha_registro',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='dienteestado',
            name='numero_diente',
            field=models.IntegerField(default=0, help_text='Número internacional del diente (11-48)'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='dienteestado',
            name='estado',
            field=models.CharField(choices=[('SANO', 'Sano'), ('CARIES', 'Caries'), ('CORONA', 'Corona'), ('AUSENTE', 'Ausente'), ('TRATADO', 'Tratado Endodoncia'), ('IMPLANTE', 'Implante')], default='SANO', max_length=20),
        ),
        migrations.AlterField(
            model_name='dienteestado',
            name='notas',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.RemoveField(
            model_name='dienteestado',
            name='diente',
        ),
    ]
