# Generated by Django 6.0.3 on 2026-04-08 15:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0011_alter_dienteestado_options_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='dienteestado',
            unique_together={('paciente', 'numero_diente')},
        ),
    ]
