# Generated by Django 6.0.3 on 2026-04-08 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0012_alter_dienteestado_unique_together'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='archivopaciente',
            name='imagen',
        ),
        migrations.AddField(
            model_name='archivopaciente',
            name='archivo',
            field=models.FileField(default='', upload_to='pacientes_archivos/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='archivopaciente',
            name='titulo',
            field=models.CharField(help_text='Ej. Radiografía Panorámica, Examen de Sangre...', max_length=100),
        ),
    ]
