# Generated by Django 6.0.3 on 2026-04-09 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0013_remove_archivopaciente_imagen_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='paciente',
            name='odontograma_data',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
