# Generated by Django 6.0.3 on 2026-04-10 12:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0014_paciente_odontograma_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='pago',
            name='metodo',
            field=models.CharField(choices=[('EFECTIVO', 'Efectivo'), ('TRANSFERENCIA', 'Transferencia'), ('TARJETA', 'Tarjeta')], default='EFECTIVO', max_length=20),
        ),
        migrations.AlterField(
            model_name='cita',
            name='paciente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='citas', to='gestion.paciente'),
        ),
        migrations.AlterField(
            model_name='pago',
            name='notas',
            field=models.CharField(blank=True, help_text='Referencia o detalle extra', max_length=200, null=True),
        ),
        migrations.DeleteModel(
            name='DienteEstado',
        ),
    ]
