# Generated by Django 6.0.3 on 2026-04-29 04:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0015_pago_metodo_alter_cita_paciente_alter_pago_notas_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pago',
            name='cita',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pagos_detalle', to='gestion.cita'),
        ),
        migrations.AlterField(
            model_name='cita',
            name='completada',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='cita',
            name='fecha',
            field=models.DateField(db_index=True),
        ),
        migrations.AlterField(
            model_name='pago',
            name='fecha',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='producto',
            name='nombre',
            field=models.CharField(db_index=True, max_length=100),
        ),
    ]
