# Generated by Django 6.0.3 on 2026-04-29 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0016_pago_cita_alter_cita_completada_alter_cita_fecha_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='producto',
            old_name='precio_compra',
            new_name='costo_unitario',
        ),
        migrations.AddField(
            model_name='producto',
            name='precio_venta_sugerido',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
