# Generated by Django 6.0.3 on 2026-04-29 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0017_rename_precio_compra_producto_costo_unitario_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tratamiento',
            old_name='costo_base',
            new_name='precio_venta',
        ),
        migrations.AlterField(
            model_name='tratamiento',
            name='precio_venta',
            field=models.DecimalField(decimal_places=2, help_text='Precio cobrado al paciente', max_digits=10),
        ),
    ]
