# Generated by Django 6.0.3 on 2026-04-29 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0018_remove_tratamiento_costo_base_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GoogleCalendarConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calendar_id', models.CharField(default='primary', max_length=255)),
                ('credentials_json', models.JSONField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=False)),
                ('last_sync', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='cita',
            name='google_event_id',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='tratamiento',
            name='color',
            field=models.CharField(default='#3b82f6', help_text='Color en formato HEX', max_length=7),
        ),
    ]
