# Generated by Django 6.0.3 on 2026-04-29 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0019_googlecalendarconfig_cita_google_event_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracionClinica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='logos/')),
                ('nombre_comercial', models.CharField(blank=True, max_length=100)),
                ('direccion', models.TextField(blank=True)),
                ('telefono_contacto', models.CharField(blank=True, max_length=20)),
                ('email_contacto', models.EmailField(blank=True, max_length=254)),
                ('duracion_cita_estandar', models.IntegerField(default=60)),
                ('horarios_atencion', models.JSONField(blank=True, default=dict)),
                ('moneda_simbolo', models.CharField(default='$', max_length=5)),
                ('impuesto_porcentaje', models.DecimalField(decimal_places=2, default=15.0, max_digits=5)),
                ('pie_pagina_recibo', models.TextField(blank=True)),
                ('whatsapp_numero', models.CharField(blank=True, max_length=20)),
                ('whatsapp_recordatorios_activos', models.BooleanField(default=False)),
            ],
        ),
    ]
