# Generated by Django 6.0.3 on 2026-04-29 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0020_configuracionclinica'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cita',
            name='completada',
        ),
        migrations.AddField(
            model_name='cita',
            name='estado',
            field=models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('CONFIRMADA', 'Confirmada'), ('COMPLETADA', 'Completada'), ('CANCELADA', 'Cancelada')], db_index=True, default='PENDIENTE', max_length=20),
        ),
    ]
