# Generated by Django 6.0.3 on 2026-04-29 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0022_producto_barcode_producto_categoria_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pago',
            name='monto_recibido',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Para calcular el cambio', max_digits=10),
        ),
    ]
