# Generated by Django 6.0.3 on 2026-04-29 21:54

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0023_pago_monto_recibido'),
    ]

    operations = [
        migrations.CreateModel(
            name='DoctorColaborador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('especialidad', models.CharField(blank=True, max_length=100)),
                ('telefono', models.CharField(blank=True, max_length=15)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('color_agenda', models.CharField(default='#3b82f6', help_text='Color para identificar sus citas', max_length=7)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.AddField(
            model_name='archivopaciente',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='tratamiento',
            name='comision_clinica_porcentaje',
            field=models.DecimalField(decimal_places=2, default=30.0, help_text='Porcentaje que se queda la clínica (ej: 30.00)', max_digits=5),
        ),
        migrations.AddField(
            model_name='cita',
            name='doctor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='citas', to='gestion.doctorcolaborador'),
        ),
    ]
