# Generated by Django 6.0.3 on 2026-04-29 22:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0024_doctorcolaborador_archivopaciente_uuid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tratamiento',
            name='doctor_referencia',
            field=models.ForeignKey(blank=True, help_text='Doctor que suele realizar este tratamiento', null=True, on_delete=django.db.models.deletion.SET_NULL, to='gestion.doctorcolaborador'),
        ),
    ]
