# Generated by Django 6.0.3 on 2026-04-30 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0026_logactividad'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracionclinica',
            name='color_primario',
            field=models.CharField(default='#2563eb', help_text='Color principal de la interfaz', max_length=7),
        ),
        migrations.AddField(
            model_name='configuracionclinica',
            name='fuente_familia',
            field=models.CharField(choices=[('Inter', 'Inter (Moderna)'), ('Outfit', 'Outfit (Premium)'), ('Roboto', 'Roboto (Clásica)')], default='Inter', max_length=50),
        ),
        migrations.AddField(
            model_name='configuracionclinica',
            name='tema_oscuro',
            field=models.BooleanField(default=False),
        ),
    ]
