# Generated by Django 6.0.3 on 2026-04-30 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0027_configuracionclinica_color_primario_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracionclinica',
            name='color_sidebar',
            field=models.CharField(default='#0f172a', help_text='Color de fondo del menú lateral', max_length=7),
        ),
    ]
