# Generated by Django 6.0.3 on 2026-04-30 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0028_configuracionclinica_color_sidebar'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracionclinica',
            name='color_fondo',
            field=models.CharField(default='#f8fafc', help_text='Color de fondo general', max_length=7),
        ),
        migrations.AddField(
            model_name='configuracionclinica',
            name='escala_interfaz',
            field=models.IntegerField(default=100, help_text='Escala de la interfaz en porcentaje'),
        ),
    ]
