# Generated by Django 6.0.3 on 2026-05-04 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0029_configuracionclinica_color_fondo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cita',
            name='estado',
            field=models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('CONFIRMADA', 'Confirmada'), ('PROGRAMADA', 'Programada'), ('EN_SALA', 'En Sala (Esperando)'), ('EN_CURSO', 'En Curso'), ('COMPLETADA', 'Completada'), ('CANCELADA', 'Cancelada'), ('REPROGRAMADA', 'Reprogramada'), ('NO_ASISTIO', 'No Asistió')], db_index=True, default='PENDIENTE', max_length=20),
        ),
    ]
