# Generated by Django 6.0.3 on 2026-05-04 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0030_alter_cita_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='tratamiento',
            name='aplica_impuestos',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tratamiento',
            name='categoria',
            field=models.CharField(choices=[('Consulta General', 'Consulta General'), ('Ortodoncia', 'Ortodoncia'), ('Periodoncia', 'Periodoncia'), ('Cirugía', 'Cirugía'), ('Estética', 'Estética')], default='Consulta General', max_length=50),
        ),
        migrations.AddField(
            model_name='tratamiento',
            name='color_etiqueta',
            field=models.CharField(default='#3b82f6', help_text='Color hexadecimal para la etiqueta', max_length=7),
        ),
        migrations.AddField(
            model_name='tratamiento',
            name='duracion_estimada',
            field=models.IntegerField(default=30, help_text='Duración en minutos'),
        ),
    ]
