# Generated by Django 6.0.3 on 2026-05-04 08:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0031_tratamiento_aplica_impuestos_tratamiento_categoria_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_lote', models.CharField(db_index=True, max_length=50)),
                ('cantidad', models.IntegerField(default=0)),
                ('fecha_caducidad', models.DateField(blank=True, db_index=True, null=True)),
                ('fecha_ingreso', models.DateField(auto_now_add=True)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lotes', to='gestion.producto')),
            ],
        ),
    ]
