# Generated by Django 6.0.3 on 2026-05-04 09:11

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0032_lote'),
    ]

    operations = [
        migrations.CreateModel(
            name='GestionGasto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(db_index=True, default=django.utils.timezone.now)),
                ('concepto', models.CharField(choices=[('Laboratorio', 'Laboratorio'), ('Nómina', 'Nómina'), ('Servicios', 'Servicios'), ('Insumos Externos', 'Insumos Externos'), ('Otros', 'Otros')], default='Otros', max_length=50)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('metodo_pago', models.CharField(choices=[('EFECTIVO', 'Efectivo'), ('TRANSFERENCIA', 'Transferencia'), ('TARJETA', 'Tarjeta')], default='EFECTIVO', max_length=20)),
                ('notas', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Gasto Financiero',
                'verbose_name_plural': 'Gastos Financieros',
                'ordering': ['-fecha'],
            },
        ),
    ]
