from django.urls import path
from . import views


urlpatterns = [
    path('', views.dashboard, name='dashboard'),
    path('magic-login/', views.magic_login, name='magic_login'),
    path('pacientes/', views.lista_pacientes, name='lista_pacientes'),
    path('citas/', views.lista_citas, name='lista_citas'),
    path('citas/nueva/', views.nueva_cita, name='nueva_cita'),
    path('pacientes/<int:pk>/', views.detalle_paciente, name='detalle_paciente'),
    path('paciente/modal/', views.modal_paciente, name='modal_paciente_crear'),
    path('paciente/modal/<int:pk>/', views.modal_paciente, name='modal_paciente_editar'),
    path('citas/<int:pk>/toggle-completada/', views.completar_cita, name='completar_cita'),
    path('tratamientos/', views.lista_tratamientos, name='lista_tratamientos'),
    path('tratamientos/guardar/', views.guardar_tratamiento, name='guardar_tratamiento'),
    path('tratamientos/nuevo/', views.gestionar_tratamiento, name='nuevo_tratamiento'),
    path('tratamientos/<int:pk>/editar/', views.gestionar_tratamiento, name='editar_tratamiento'),
    path('pacientes/<int:pk>/pagos/nuevo/', views.registrar_pago, name='registrar_pago'),
    path('pacientes/<int:pk>/archivos/subir/', views.subir_archivo, name='subir_archivo'),
    path('calendario/', views.calendario, name='calendario'),
    path('api/citas/', views.citas_json, name='citas_json'),
    path('calendario/guardar/', views.guardar_cita_calendario, name='guardar_cita_calendario'),
    path('pacientes/<int:pk>/receta/nueva/', views.nueva_receta, name='nueva_receta'),
    path('recetas/<int:pk>/imprimir/', views.imprimir_receta, name='imprimir_receta'),
    path('pacientes/exportar/excel/', views.exportar_pacientes_excel, name='exportar_excel'),
    path('pacientes/<int:pk>/estado-cuenta/', views.estado_cuenta_pdf, name='estado_cuenta'),
    
    # Inventario
    path('inventario/', views.inventario, name='inventario'),
    path('inventario/crear/', views.crear_producto, name='crear_producto'),
    path('inventario/movimiento/', views.registrar_movimiento, name='registrar_movimiento'),
    path('inventario/historial/', views.historial_movimientos, name='historial_movimientos'),
    path('inventario/historial/<int:producto_id>/', views.historial_movimientos, name='historial_producto'),
    
    path('citas/finalizar/<int:pk>/', views.finalizar_cita, name='finalizar_cita'),
    path('paciente/<int:pk>/', views.detalle_paciente, name='detalle_paciente'),
    path('api/paciente/<int:paciente_id>/actualizar-diente/', views.actualizar_diente, name='actualizar_diente'),
    path('finanzas/', views.reporte_finanzas, name='reporte_finanzas'),
    path('cita/completar/<int:cita_id>/', views.completar_cita_con_pago, name='completar_cita_pago'),
    path('paciente/<int:paciente_id>/nueva-cita-modal/', views.modal_nueva_cita, name='modal_nueva_cita'),
    path('paciente/<int:paciente_id>/odontograma/api/', views.api_odontograma, name='api_odontograma'),
    path('api/citas/reprogramar/', views.reprogramar_cita, name='reprogramar_cita'),
    path('google/init/', views.google_calendar_init, name='google_init'),
    path('google/callback/', views.google_calendar_callback, name='google_callback'),
    path('configuracion/', views.panel_configuracion, name='panel_configuracion'),
    path('api/dashboard/stats/', views.api_dashboard_stats, name='api_dashboard_stats'),
    path('pagos/<int:pago_id>/ticket/', views.imprimir_ticket_pago, name='imprimir_ticket'),
    path('pacientes/<int:pk>/editar-rapido/', views.editar_paciente_rapido, name='editar_paciente_rapido'),
    path('staff/', views.gestion_doctores, name='gestion_doctores'),
]
