"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 6.0.3.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""
import os
from pathlib import Path
from dotenv import load_dotenv

# Cargar variables de entorno desde el archivo .env
load_dotenv()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv('SECRET_KEY', 'django-insecure-default-change-me')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv('DEBUG', 'True') == 'True'

ALLOWED_HOSTS = ['herxull.pythonanywhere.com', 'www.herxull.pythonanywhere.com', 'localhost', '.localhost', '127.0.0.1', '.test-clinica.com', '.nip.io', '.127.0.0.1.nip.io']


# Application definition

SHARED_APPS = (
    'django_tenants',  # Â¡Debe ser el primero obligatoriamente!

    'clientes',  # Tu nueva app de administraciÃ³n de clÃ­nicas

    'django.contrib.contenttypes',
    'django.contrib.auth',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.admin',
)

TENANT_APPS = (
    # AquÃ­ van las apps que cada clÃ­nica tendrÃ¡ para sÃ­ misma
    'django.contrib.contenttypes',
    'django.contrib.auth',
    'django.contrib.sessions',
    'django.contrib.messages',

    'gestion',  # Â¡AquÃ­ estÃ¡ tu app dental!
)

INSTALLED_APPS = list(SHARED_APPS) + [app for app in TENANT_APPS if app not in SHARED_APPS]

TENANT_MODEL = "clientes.Clinica" # El modelo que define los esquemas
TENANT_DOMAIN_MODEL = "clientes.Dominio" # El modelo que enruta las URLs

DATABASE_ROUTERS = (
    'django_tenants.routers.TenantSyncRouter',
)

MIDDLEWARE = [
    'django_tenants.middleware.main.TenantMainMiddleware',
    'clientes.middleware.TrialExpirationMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

# Esta es la ruta para las clÃ­nicas (Tenants)
ROOT_URLCONF = 'config.urls'
PUBLIC_SCHEMA_URLCONF = 'config.urls_publicas'

# ConfiguraciÃ³n para evitar 404 si no se detecta el tenant (cae al pÃºblico)
SHOW_PUBLIC_IF_NO_TENANT_FOUND = True

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'gestion.context_processors.clinica_config',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Configuración de Correo Electrónico
EMAIL_BACKEND = os.getenv('EMAIL_BACKEND', 'django.core.mail.backends.console.EmailBackend')
DEFAULT_FROM_EMAIL = os.getenv('DEFAULT_FROM_EMAIL', 'DentalSaaS <noreply@dentalsaas.com>')

# Configuración de Logs (Fundamental para SaaS comercial)
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '{levelname} {asctime} {module} {process:d} {thread:d} {message}',
            'style': '{',
        },
    },
    'handlers': {
        'file': {
            'level': 'ERROR',
            'class': 'logging.FileHandler',
            'filename': os.path.join(BASE_DIR, 'error_criticos.log'),
            'formatter': 'verbose',
        },
        'console': {
            'class': 'logging.StreamHandler',
        },
    },
    'loggers': {
        'django': {
            'handlers': ['console', 'file'],
            'level': 'INFO',
            'propagate': True,
        },
    },
}


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django_tenants.postgresql_backend',
        'NAME': os.getenv('DB_NAME', 'postgres'),
        'USER': os.getenv('DB_USER', 'postgres'),
        'PASSWORD': os.getenv('DB_PASSWORD', ''),
        'HOST': os.getenv('DB_HOST', 'localhost'),
        'PORT': os.getenv('DB_PORT', '5432'),
        'OPTIONS': {
            'sslmode': 'require',
        }
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'es-ni'

TIME_ZONE = 'America/Managua'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'
MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

# Sesiones y Autenticación Multi-Tenant
SESSION_COOKIE_DOMAIN = None if DEBUG else '.dentalsaas.com'
LOGIN_URL = '/accounts/login/'
LOGIN_REDIRECT_URL = '/'
# Redirigir a la pantalla de login al cerrar sesiÃ³n
LOGOUT_REDIRECT_URL = 'login'

AUTHENTICATION_BACKENDS = [
    # 'config.backends.EmailOrUsernameBackend',
    'django.contrib.auth.backends.ModelBackend',
]

STATIC_ROOT = os.path.join(BASE_DIR, 'static')

CSRF_TRUSTED_ORIGINS = ['https://herxull.pythonanywhere.com', 'http://localhost:8000', 'http://*.localhost:8000']

# ConfiguraciÃ³n de Logs Profesionales
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'tenant_format': {
            'format': '[%(asctime)s] [%(levelname)s] [%(name)s] [Tenant:%(tenant_name)s] [User:%(user_id)s] %(message)s'
        },
    },
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
        },
        'file': {
            'level': 'INFO',
            'class': 'logging.FileHandler',
            'filename': os.path.join(BASE_DIR, 'audit_access.log'),
            'formatter': 'tenant_format',
        },
    },
    'loggers': {
        'gestion.audit': {
            'handlers': ['console', 'file'],
            'level': 'INFO',
            'propagate': True,
        },
    },
}

# Seguridad de Archivos: Prefijar carpetas de medios por esquema
import django_tenants.utils
MULTITENANT_RELATIVE_MEDIA_ROOT = "" # Los archivos se guardarÃ¡n en MEDIA_ROOT/schema_name/


# CONFIGURACIÓN GOOGLE CALENDAR (Cargada de forma segura desde .env)
GOOGLE_CLIENT_ID = os.getenv('GOOGLE_OAUTH_CLIENT_ID')
GOOGLE_CLIENT_SECRET = os.getenv('GOOGLE_OAUTH_CLIENT_SECRET')
GOOGLE_REDIRECT_URI = os.getenv('GOOGLE_REDIRECT_URI', 'http://localhost:8000/google/callback/')

# CONFIGURACIÓN 2CHECKOUT
TWO_CHECKOUT_MERCHANT_ID = os.getenv('TWO_CHECKOUT_MERCHANT_ID')
TWO_CHECKOUT_SECRET_KEY = os.getenv('TWO_CHECKOUT_SECRET_KEY')
TWO_CHECKOUT_SECRET_WORD = os.getenv('TWO_CHECKOUT_SECRET_WORD')
TWO_CHECKOUT_BUY_LINK = os.getenv('TWO_CHECKOUT_BUY_LINK')
CURRENCY = os.getenv('CURRENCY', 'USD')
# Desactivar COOP en desarrollo para evitar bloqueos por origen no confiable
SECURE_CROSS_ORIGIN_OPENER_POLICY = None
