# Generated by Django 6.0.3 on 2026-04-29 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='clinica',
            name='gastos_fijos',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
