# Generated by Django 6.0.3 on 2026-04-29 19:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0002_clinica_gastos_fijos'),
    ]

    operations = [
        migrations.AddField(
            model_name='clinica',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='clinica',
            name='is_trial',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='clinica',
            name='trial_end_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='clinica',
            name='trial_start_date',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2026, 4, 29, 19, 39, 19, 164969, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
    ]
