# Generated by Django 6.0.3 on 2026-04-29 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0003_clinica_is_active_clinica_is_trial_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='clinica',
            name='stripe_customer_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='clinica',
            name='stripe_subscription_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
