# Generated by Django 6.0.3 on 2026-04-29 21:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0004_clinica_stripe_customer_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clinica',
            name='stripe_customer_id',
        ),
        migrations.RemoveField(
            model_name='clinica',
            name='stripe_subscription_id',
        ),
        migrations.CreateModel(
            name='Suscripcion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan_tipo', models.CharField(choices=[('BASICO', 'Básico'), ('PRO', 'Profesional')], default='PRO', max_length=20)),
                ('estado_pago', models.CharField(choices=[('PENDIENTE', 'Pendiente de Pago'), ('VALIDACION', 'Pendiente de Validación (Manual)'), ('APROBADO', 'Aprobado / Activo'), ('RECHAZADO', 'Rechazado / Expirado')], default='PENDIENTE', max_length=20)),
                ('metodo_pago', models.CharField(choices=[('2CHECKOUT', 'Tarjeta (2Checkout)'), ('TRANSFERENCIA', 'Transferencia Bancaria')], max_length=20)),
                ('fecha_inicio', models.DateTimeField(auto_now_add=True)),
                ('fecha_vencimiento', models.DateTimeField(blank=True, null=True)),
                ('comprobante_img', models.ImageField(blank=True, null=True, upload_to='comprobantes/%Y/%m/')),
                ('notas_admin', models.TextField(blank=True, null=True)),
                ('external_reference', models.CharField(blank=True, max_length=100, null=True)),
                ('clinica', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suscripciones', to='clientes.clinica')),
            ],
        ),
    ]
