# Generated by Django 6.0.3 on 2026-04-29 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0005_remove_clinica_stripe_customer_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='suscripcion',
            name='estado_pago',
            field=models.CharField(choices=[('TRIAL', 'Periodo de Prueba'), ('PENDIENTE', 'Pendiente de Pago'), ('VALIDACION', 'Pendiente de Validación (Manual)'), ('APROBADO', 'Aprobado / Activo'), ('RECHAZADO', 'Rechazado / Expirado')], default='PENDIENTE', max_length=20),
        ),
    ]
