# Generated by Django 6.0.3 on 2026-04-29 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0006_alter_suscripcion_estado_pago'),
    ]

    operations = [
        migrations.AlterField(
            model_name='suscripcion',
            name='metodo_pago',
            field=models.CharField(choices=[('2CHECKOUT', 'Tarjeta (2Checkout)'), ('TRANSFERENCIA', 'Transferencia Bancaria'), ('GRATIS', 'Cortesía / Trial')], max_length=20),
        ),
    ]
