# Generated by Django 6.0.3 on 2026-04-30 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0007_alter_suscripcion_metodo_pago'),
    ]

    operations = [
        migrations.AddField(
            model_name='clinica',
            name='auto_renovacion',
            field=models.BooleanField(default=False),
        ),
    ]
