# Generated by Django 6.0.3 on 2026-04-30 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0009_alter_suscripcion_estado_pago'),
    ]

    operations = [
        migrations.AddField(
            model_name='clinica',
            name='email_contacto',
            field=models.EmailField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='suscripcion',
            name='metodo_pago',
            field=models.CharField(choices=[('2CHECKOUT', 'Tarjeta (2Checkout)'), ('TRANSFERENCIA', 'Transferencia Bancaria'), ('CORTESIA', 'Mes de Cortesía'), ('GRATIS', 'Periodo de Prueba (Trial)')], max_length=20),
        ),
    ]
